name: Analyze TestRay results

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1-5'

jobs:
  analyze-testray-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Analyze TestRay results
        env:
          TESTRAY_CLIENT_ID: ${{ secrets.TESTRAY_CLIENT_ID }}
          TESTRAY_CLIENT_SECRET: ${{ secrets.TESTRAY_CLIENT_SECRET }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_API_USER: ${{ secrets.JIRA_API_USER }}
        run: python3 ./scripts/python/analyze_testray_results.py

